2023-04-18 00:48:57,106 TADA INFO starting test `direct_ldms_ls_conn_test`
2023-04-18 00:48:57,106 TADA INFO   test-id: b988cf4f1c6ba01128138668d9f8ac784aecdb6d0defadd57619591379416738
2023-04-18 00:48:57,107 TADA INFO   test-suite: LDMSD
2023-04-18 00:48:57,107 TADA INFO   test-name: direct_ldms_ls_conn_test
2023-04-18 00:48:57,107 TADA INFO   test-user: narate
2023-04-18 00:48:57,107 TADA INFO   commit-id: b36fe782e0bfd073a535d0c799fb7583402519e3
2023-04-18 00:48:57,333 __main__ INFO starting munged on cygnus-01-iw
2023-04-18 00:48:57,629 __main__ INFO starting munged on localhost
2023-04-18 00:48:57,873 __main__ INFO starting ldmsd on cygnus-01-iw
2023-04-18 00:48:58,212 TADA INFO assertion 0, Start ldmsd sampler and munged: OK, passed
2023-04-18 00:49:03,320 TADA INFO assertion 1, ldms_ls to the sampler: ldms_ls failed, output:
Tue Apr 18 00:49:03 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential
Connection failed/rejected.
, failed
Traceback (most recent call last):
  File "direct_ldms_ls_conn_test", line 281, in <module>
    raise RuntimeError("ldms_ls rc: {}".format(rc))
RuntimeError: ldms_ls rc: 1
2023-04-18 00:49:03,321 TADA INFO assertion 2, Kill the sampler: skipped
2023-04-18 00:49:03,322 TADA INFO assertion 3, ldms_ls to the dead sampler: skipped
2023-04-18 00:49:03,322 TADA INFO assertion 4, ldms_ls to a dead host: skipped
2023-04-18 00:49:03,322 TADA INFO test direct_ldms_ls_conn_test ended
2023-04-18 00:49:03,527 __main__ INFO stopping munged on cygnus-01-iw
2023-04-18 00:49:03,946 __main__ INFO stopping munged on localhost
