2023-05-10 01:07:00,659 TADA INFO starting test `ldmsd_auth_test`
2023-05-10 01:07:00,660 TADA INFO   test-id: 31653fee287981d0a2f7267b65cdb55b307ad3fca124011656e4013d1abd6de2
2023-05-10 01:07:00,660 TADA INFO   test-suite: LDMSD
2023-05-10 01:07:00,660 TADA INFO   test-name: ldmsd_auth_test
2023-05-10 01:07:00,660 TADA INFO   test-user: narate
2023-05-10 01:07:00,660 TADA INFO   commit-id: 7b372c6c113ec487de8c386689e854d2a05d7299
2023-05-10 01:07:00,660 __main__ INFO -- Get or create the cluster --
2023-05-10 01:07:18,764 __main__ INFO -- Start daemons --
2023-05-10 01:07:37,681 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-05-10 01:07:42,801 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-05-10 01:07:42,925 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-05-10 01:07:43,050 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-05-10 01:07:43,161 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-05-10 01:07:43,274 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Wed May 10 01:07:43 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-05-10 01:07:43,275 TADA INFO test ldmsd_auth_test ended
