2023-05-11 01:06:52,357 TADA INFO starting test `ldmsd_auth_test`
2023-05-11 01:06:52,357 TADA INFO   test-id: cf1cfb78a5e03dd92002e22e23aefbb9292ea71210e9637882403024104841b8
2023-05-11 01:06:52,357 TADA INFO   test-suite: LDMSD
2023-05-11 01:06:52,357 TADA INFO   test-name: ldmsd_auth_test
2023-05-11 01:06:52,357 TADA INFO   test-user: narate
2023-05-11 01:06:52,357 TADA INFO   commit-id: bf615e117c95b472fcd0941ff4734b25cb7cbaf9
2023-05-11 01:06:52,358 __main__ INFO -- Get or create the cluster --
2023-05-11 01:07:10,684 __main__ INFO -- Start daemons --
2023-05-11 01:07:29,575 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-05-11 01:07:34,705 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-05-11 01:07:34,829 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-05-11 01:07:34,948 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-05-11 01:07:35,069 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-05-11 01:07:35,183 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Thu May 11 01:07:35 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-05-11 01:07:35,183 TADA INFO test ldmsd_auth_test ended
