2023-03-30 01:02:34,164 TADA INFO starting test `ldmsd_auth_test`
2023-03-30 01:02:34,164 TADA INFO   test-id: bd9969cc91a192128b36ee652e2336e1697d4aedce0e40e4e85bab7b3dab96cd
2023-03-30 01:02:34,164 TADA INFO   test-suite: LDMSD
2023-03-30 01:02:34,164 TADA INFO   test-name: ldmsd_auth_test
2023-03-30 01:02:34,164 TADA INFO   test-user: narate
2023-03-30 01:02:34,164 TADA INFO   commit-id: 21baf08f6cc91323a5fd20bf2a1498a48cd12731
2023-03-30 01:02:34,165 __main__ INFO -- Get or create the cluster --
2023-03-30 01:02:52,353 __main__ INFO -- Start daemons --
2023-03-30 01:03:11,272 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-03-30 01:03:16,416 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-03-30 01:03:16,536 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-03-30 01:03:16,642 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-03-30 01:03:16,767 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-03-30 01:03:16,878 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Thu Mar 30 01:03:16 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-03-30 01:03:16,879 TADA INFO test ldmsd_auth_test ended
