2023-04-13 01:02:33,478 TADA INFO starting test `ldmsd_auth_test`
2023-04-13 01:02:33,479 TADA INFO   test-id: 3fb9b670d2472a67976b2f0bbc74b71f65b2ea524cd2ca214209d3e4742c1edb
2023-04-13 01:02:33,479 TADA INFO   test-suite: LDMSD
2023-04-13 01:02:33,479 TADA INFO   test-name: ldmsd_auth_test
2023-04-13 01:02:33,479 TADA INFO   test-user: narate
2023-04-13 01:02:33,479 TADA INFO   commit-id: 94a9b7ad0a9ffdf9152fdb494060db1352ad8238
2023-04-13 01:02:33,480 __main__ INFO -- Get or create the cluster --
2023-04-13 01:02:51,307 __main__ INFO -- Start daemons --
2023-04-13 01:03:10,336 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-04-13 01:03:15,491 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-04-13 01:03:15,615 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-04-13 01:03:15,738 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-04-13 01:03:15,845 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-04-13 01:03:15,971 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Thu Apr 13 01:03:15 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-04-13 01:03:15,972 TADA INFO test ldmsd_auth_test ended
