2023-05-06 01:07:21,891 TADA INFO starting test `ldmsd_auth_test`
2023-05-06 01:07:21,891 TADA INFO   test-id: 7f8d54f9d097efeca499af2139db6e146249c7bb7c0f20884b3eb96d8ef2313e
2023-05-06 01:07:21,891 TADA INFO   test-suite: LDMSD
2023-05-06 01:07:21,891 TADA INFO   test-name: ldmsd_auth_test
2023-05-06 01:07:21,891 TADA INFO   test-user: narate
2023-05-06 01:07:21,891 TADA INFO   commit-id: c7f935ea14b1559e0062b36bbaf3358d515ce391
2023-05-06 01:07:21,892 __main__ INFO -- Get or create the cluster --
2023-05-06 01:07:39,934 __main__ INFO -- Start daemons --
2023-05-06 01:07:58,811 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-05-06 01:08:03,935 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-05-06 01:08:04,050 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-05-06 01:08:04,172 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-05-06 01:08:04,284 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-05-06 01:08:04,413 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Sat May 06 01:08:04 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-05-06 01:08:04,413 TADA INFO test ldmsd_auth_test ended
