2023-04-09 01:02:46,611 TADA INFO starting test `ldmsd_auth_test`
2023-04-09 01:02:46,611 TADA INFO   test-id: e44c5ff327909c4f1c6122ae11f5b8619016f3a8ecba05c34c8a91cf4a52aabc
2023-04-09 01:02:46,611 TADA INFO   test-suite: LDMSD
2023-04-09 01:02:46,611 TADA INFO   test-name: ldmsd_auth_test
2023-04-09 01:02:46,611 TADA INFO   test-user: narate
2023-04-09 01:02:46,611 TADA INFO   commit-id: 21baf08f6cc91323a5fd20bf2a1498a48cd12731
2023-04-09 01:02:46,612 __main__ INFO -- Get or create the cluster --
2023-04-09 01:03:04,305 __main__ INFO -- Start daemons --
2023-04-09 01:03:23,102 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-04-09 01:03:28,234 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-04-09 01:03:28,357 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-04-09 01:03:28,471 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-04-09 01:03:28,586 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-04-09 01:03:28,695 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Sun Apr 09 01:03:28 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-04-09 01:03:28,695 TADA INFO test ldmsd_auth_test ended
