2023-05-02 01:06:47,251 TADA INFO starting test `ldmsd_auth_test`
2023-05-02 01:06:47,251 TADA INFO   test-id: 4a89c7c2c69b52ab20d60492dedece309cd61cf2875ad3c622da0ce32579b490
2023-05-02 01:06:47,251 TADA INFO   test-suite: LDMSD
2023-05-02 01:06:47,251 TADA INFO   test-name: ldmsd_auth_test
2023-05-02 01:06:47,251 TADA INFO   test-user: narate
2023-05-02 01:06:47,252 TADA INFO   commit-id: a2b506e743a3264bf3a6a3fbb0a9099088cd911e
2023-05-02 01:06:47,252 __main__ INFO -- Get or create the cluster --
2023-05-02 01:07:05,067 __main__ INFO -- Start daemons --
2023-05-02 01:07:24,057 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-05-02 01:07:29,190 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-05-02 01:07:29,310 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-05-02 01:07:29,418 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-05-02 01:07:29,539 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-05-02 01:07:29,649 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Tue May 02 01:07:29 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-05-02 01:07:29,649 TADA INFO test ldmsd_auth_test ended
