2023-06-03 01:07:42,891 TADA INFO starting test `ldmsd_auth_test`
2023-06-03 01:07:42,891 TADA INFO   test-id: 86bdd88353ae65ed26c3608bd121c4d5a893fb3f752cd5961bfda9fc1463c01a
2023-06-03 01:07:42,891 TADA INFO   test-suite: LDMSD
2023-06-03 01:07:42,891 TADA INFO   test-name: ldmsd_auth_test
2023-06-03 01:07:42,891 TADA INFO   test-user: narate
2023-06-03 01:07:42,891 TADA INFO   commit-id: d403a90da67ae0dc1d9ef66d720f6227e28c1ace
2023-06-03 01:07:42,892 __main__ INFO -- Get or create the cluster --
2023-06-03 01:08:01,019 __main__ INFO -- Start daemons --
2023-06-03 01:08:20,160 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-06-03 01:08:25,314 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-06-03 01:08:25,441 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-06-03 01:08:25,574 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-06-03 01:08:25,677 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-06-03 01:08:25,783 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Sat Jun 03 01:08:25 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-06-03 01:08:25,783 TADA INFO test ldmsd_auth_test ended
