2025-01-10 05:09:22,406 TADA INFO starting test `maestro_cfg_test`
2025-01-10 05:09:22,407 TADA INFO   test-id: 23d800217943ebd2e3c3e9b4f95d16df1185eb1b6305347e429845526687e068
2025-01-10 05:09:22,407 TADA INFO   test-suite: LDMSD
2025-01-10 05:09:22,407 TADA INFO   test-name: maestro_cfg_test
2025-01-10 05:09:22,407 TADA INFO   test-user: narate
2025-01-10 05:09:22,407 TADA INFO   commit-id: 62821d188422d18bc6e8ce2109189c8855865aab
2025-01-10 05:09:32,419 __main__ INFO -- Get or create cluster --
2025-01-10 05:10:17,149 __main__ INFO -- Start daemons --
2025-01-10 05:10:32,302 __main__ INFO ... make sure ldmsd's are up
2025-01-10 05:10:37,879 TADA INFO assertion 1, load maestro etcd cluster: Unexpected output: , failed
---Wait for config to write to file---
Traceback (most recent call last):
  File "maestro_cfg_test", line 324, in <module>
    test.assert_test(1, False, "Unexpected output: {}".format(out))
  File "/home/narate/cron/ldms-test-b4.4/TADA.py", line 157, in assert_test
    raise AssertionException(self.test_desc + ", " + cond_str + ": FAILED")
TADA.AssertionException: Test for ldmsd configuration with maestro_ctrl, Unexpected output: : FAILED
2025-01-10 05:10:37,880 TADA INFO assertion 2, config ldmsd cluster with maestro: skipped
2025-01-10 05:10:37,880 TADA INFO assertion 3, verify sampler daemons: skipped
2025-01-10 05:10:37,880 TADA INFO assertion 4, verify L1 aggregator daemons: skipped
2025-01-10 05:10:37,881 TADA INFO assertion 5, verify L2 aggregator daemon: skipped
2025-01-10 05:10:37,881 TADA INFO assertion 6, verify data storage: skipped
2025-01-10 05:10:37,881 TADA INFO test maestro_cfg_test ended
