2023-07-05 01:18:00,647 TADA INFO starting test `slurm_sampler2_test`
2023-07-05 01:18:00,647 TADA INFO   test-id: e908750a6fdfcda5a0c1cfa48249402b9de123971b4486da48bf4b246a3d69cb
2023-07-05 01:18:00,647 TADA INFO   test-suite: LDMSD
2023-07-05 01:18:00,647 TADA INFO   test-name: slurm_sampler2_test
2023-07-05 01:18:00,648 TADA INFO   test-user: narate
2023-07-05 01:18:00,648 TADA INFO   commit-id: 636a1c6eed94acbb98f830d7507cbfe1ed9a92a0
2023-07-05 01:18:00,648 __main__ INFO -- Get or create the cluster --
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/networks/narate-slurm_sampler2_test-636a1c6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 685, in _get
    net = dc.networks.get(name)
  File "/usr/lib/python3.6/site-packages/docker/models/networks.py", line 180, in get
    self.client.api.inspect_network(network_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/network.py", line 213, in inspect_network
    return self._result(res, json=True)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("network narate-slurm_sampler2_test-636a1c6 not found")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1619, in get
    cluster = _cls._get(name)
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 688, in _get
    raise LookupError()
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/71bf7ce790fec9319c3686a2925e822b69a490a162d9bcbd099774fe13e02502/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "slurm_sampler2_test", line 736, in <module>
    cluster = LDMSDCluster.get(spec["name"], create = True, spec = spec)
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1626, in get
    return _cls.create(spec)
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1597, in create
    cluster = _cls._create(spec)
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 419, in _create
    return cls.__create(spec=sp, **kwargs)
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 599, in __create
    cluster.update_etc_hosts(node_aliases = node_aliases)
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1705, in update_etc_hosts
    cont.write_file("/etc/hosts", etc_hosts)
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 204, in write_file
    rc, sock = self._exec_run(cmd, stdin=True, socket=True, user = user)
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 147, in _exec_run
    self.wait_running()
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 137, in wait_running
    self.obj.reload()
  File "/usr/lib/python3.6/site-packages/docker/models/resource.py", line 48, in reload
    new_model = self.collection.get(self.id)
  File "/usr/lib/python3.6/site-packages/docker/models/containers.py", line 880, in get
    resp = self.client.api.inspect_container(container_id)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/container.py", line 758, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: 71bf7ce790fec9319c3686a2925e822b69a490a162d9bcbd099774fe13e02502")
2023-07-05 01:18:12,486 TADA INFO assertion 1, Processing the stream data from slurm_notifier: skipped
2023-07-05 01:18:12,486 TADA INFO assertion 2.1, Deleting completed jobs -- job_init: skipped
2023-07-05 01:18:12,486 TADA INFO assertion 3.1, Expanding the set heap -- job_init: skipped
2023-07-05 01:18:12,486 TADA INFO assertion 4.1, Multi-tenant -- job_init: skipped
2023-07-05 01:18:12,486 TADA INFO assertion 2.2, Deleting completed jobs -- step_init: skipped
2023-07-05 01:18:12,486 TADA INFO assertion 3.2, Expanding the set heap -- step_init: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 4.2, Multi-tenant -- step_init: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 2.3, Deleting completed jobs -- task_init: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 3.3, Expanding the set heap -- task_init: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 4.3, Multi-tenant -- task_init: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 2.4, Deleting completed jobs -- task_exit: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 3.4, Expanding the set heap -- task_exit: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 4.4, Multi-tenant -- task_exit: skipped
2023-07-05 01:18:12,487 TADA INFO assertion 2.5, Deleting completed jobs -- job_exit: skipped
2023-07-05 01:18:12,488 TADA INFO assertion 3.5, Expanding the set heap -- job_exit: skipped
2023-07-05 01:18:12,488 TADA INFO assertion 4.5, Multi-tenant -- job_exit: skipped
2023-07-05 01:18:12,488 TADA INFO test slurm_sampler2_test ended
