2023-05-06 01:41:55,882 __main__ INFO -- Get or create the cluster --
2023-05-06 01:41:55,883 TADA INFO starting test `store_sos_lists_test`
2023-05-06 01:41:55,883 TADA INFO   test-id: ccf868a80b8003307d2f2e2a7e1f579b7bdf85ff89b8ada239280f9a5ee388fa
2023-05-06 01:41:55,883 TADA INFO   test-suite: LDMSD
2023-05-06 01:41:55,883 TADA INFO   test-name: store_sos_lists_test
2023-05-06 01:41:55,883 TADA INFO   test-user: narate
2023-05-06 01:41:55,883 TADA INFO   commit-id: c7f935ea14b1559e0062b36bbaf3358d515ce391
2023-05-06 01:42:03,274 __main__ INFO Waiting ... for all LDMSDs to start
2023-05-06 01:42:07,100 __main__ INFO All sampler daemons are up.
2023-05-06 01:42:07,211 TADA INFO assertion 1, aggregator with store_sos has started properly.: agg_sos.check_ldmsd(), passed
2023-05-06 01:42:07,320 TADA INFO assertion 2, aggregator with store_csv has started properly.: agg_csv.check_ldmsd(), passed
2023-05-06 01:42:13,380 TADA INFO assertion 3, store_sos is storing data.: file_exists(a) for a in supported_schema, passed
2023-05-06 01:42:14,593 TADA INFO assertion 4, store_sos stores data correctly.: verify_data(db) for db in all_db, passed
2023-05-06 01:42:23,497 TADA INFO assertion 5, store_sos stores data after restarted correctly.: verify_data(db) for db in all_db, passed
2023-05-06 01:42:24,117 TADA INFO assertion 6, store_sos reports multiple list errror messages resulted by the config file.: store_sos reported the multiple list error messages., passed
2023-05-06 01:42:28,913 TADA INFO assertion 7, store_sos reports multiple list errror messages resulted by ldmsd_controller.: store_sos reported the multiple list error messages., passed
2023-05-06 01:42:29,235 TADA INFO assertion 8, store_csv is storing data.: file_exists(a) for a in supported_schema, passed
2023-05-06 01:42:35,672 TADA INFO assertion 9, store_csv stores data correctly.: verify_data(db) for db in all_db, passed
Traceback (most recent call last):
  File "store_list_record_test", line 571, in <module>
    good, reason = verify_data(num_lists, schema, data)
  File "store_list_record_test", line 345, in verify_data
    round0 = data[0]["round"] # First line of data
IndexError: list index out of range
2023-05-06 01:42:45,123 TADA INFO assertion 10, store_csv stores data after restarted correctly.: skipped
2023-05-06 01:42:45,123 TADA INFO assertion 11, store_csv reports multiple list errror messages resulted by the config file.: skipped
2023-05-06 01:42:45,123 TADA INFO assertion 12, store_csv reports multiple list errror messages resulted by ldmsd_controller.: skipped
2023-05-06 01:42:45,123 TADA INFO test store_sos_lists_test ended
